### ISSUE TITLE
Warning issued for %files targets

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#101]
## Expected Behavior

No warning

## Actual Behavior

Warning if target of copy does not exist

Line: https://github.com/singularityhub/singularity-cli/blob/7893bddf592a1b2ec884c529ed2a9eef2ad92670/spython/main/parse/docker.py#L213

## Possible Fix

Show warning only for the "source" part. Checking the destination simply makes no sense

**Comment by vsoch** [comment]
What about a slight alternative where we look for the file existing OR the directory - the logic being to copy a folder or files to some spot, the parent directory needs to exist. I propose something like:

```python
            # Warning if doesn't exist
            if not os.path.exists(path) and not os.path.exists(os.path.dirname(path)):
                bot.warning("%s doesn't exist, ensure exists for build" %path)
```
Thoughts?

**Comment by Flamefire** [comment]
It does not make sense at all to check the existence of (part of) destination path
The destination is inside the container. It cannot exist 

Or am I missing anything?

**Comment by vsoch** [comment]
Yeah you’re right - I’m not thinking clearly about this. I’ll update the PR in a bit.

**Comment by vsoch** [comment]
Just updated the PR.
