### ISSUE TITLE
Add warning for file expansion for files/folders in %files section

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#102]
**Describe the solution you'd like**

DockerFiles allow copies of `*.py` or `myFolder`. spython could expand the wildcard options to actual files (if existing) and traverse the folder (if existing) to copy individual files. This is not perfect but handles the shortcoming of singularity def file format in the spirit of reproducibility (explicit list instead of wildcards)

**Describe alternatives you've considered**
Show an error if such things (wildcard, folder, ...) are found as the image WILL be broken.

**Comment by vsoch** [comment]
I see this as an issue that should be addressed upstream with Singularity, which should support the same file references as Docker. Doing a hacky fix here isn't the best approach to address this. I suggest that you open an issue there.

**Comment by Flamefire** [comment]
What about the described alternative? That would be the user-friendly solution.

**Comment by vsoch** [comment]
That's definitely reasonable, when you have time and open your PR for #103 this would be good to add!
