### ISSUE TITLE
Format code with yapf

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#113]
I suggest to use [yapf](https://github.com/google/yapf) to unify the format of the code. It is basically like clang-format combined with autopep8 and works well. I can provide a format file with minimal changes to the defaults which we used in another project.

Format issues I've seen consist mainly in
- wrong indentation (missing space in front)
- missing space after comma
- trailing space
- missing spaces around binary ops
- superflous space in arguments

Best used is to add yapf as a submodule for developers only and enforce on CI

**Comment by vsoch** [comment]
@Flamefire I've been using black (and I like it a lot). Have you tried it out?

**Comment by vsoch** [comment]
The code is now formatted (and checked) with black, closing issue. Thanks for the suggestion!
