### ISSUE TITLE
CD to WORKDIR is missing in singularity runscript

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#114]
## Expected Behavior

ENTRYPOINT command is executed in WORKDIR

## Actual Behavior

ENTRYPOINT is executed in HOME

## Steps to Reproduce

Convert Dockerfile containing both to singularity file an watch the %runscript section

## Possible Fix

Add cd before the command

**Comment by vsoch** [comment]
Even if change is needed, it's easy enough to fix this issue (and another bug I found) https://github.com/singularityhub/singularity-cli/pull/115
