### ISSUE TITLE
Python 2 tests run with python3

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#118]
Short: Conda for Python2 and Python3 are installed into the same, cached dir on CircleCI which causes a race condition in which currently the Python2 jobs run with Python3

**Comment by vsoch** [comment]
Ouch.

**Comment by Flamefire** [comment]
BTW: Is Python2 compatibility still required or can it be dropped?

**Comment by vsoch** [comment]
oy vey, I'd say that we at least support it until it's officially smooshed. I'd like to do it sooner, but there are still a lot of clusters that are supporting old Python, and likely they won't update until it's absolutely necessary.

**Comment by vsoch** [comment]
Also, if we are going to update test_oci, and we are using the Circle Orb to build, I'll need to update that for 3.2.1.

**Comment by vsoch** [comment]
Nevermind, we can change `singularity-version` and `go-version` :)

**Comment by Flamefire** [comment]
Not really. I added a check for `>= 3.2.1` :)
