### ISSUE TITLE
spython recipe "TypeError: super() takes at least 1 argument (0 given)"

### ISSUE THREAD

**Issue by remyd1** [singularityhub/singularity-cli#12]
Hi,

From the latest stable version, each try to convert a recipe failing to:

```
Traceback (most recent call last):
  File "/usr/local/bin/spython", line 9, in <module>
    load_entry_point('spython==0.0.22', 'console_scripts', 'spython')()
  File "/usr/local/lib/python2.7/dist-packages/spython-0.0.22-py2.7.egg/spython/client/__init__.py", line 167, in main
    main(args=args, options=options, parser=parser)
  File "/usr/local/lib/python2.7/dist-packages/spython-0.0.22-py2.7.egg/spython/client/recipe.py", line 51, in main
    parser = parser(args.files[0])
  File "/usr/local/lib/python2.7/dist-packages/spython-0.0.22-py2.7.egg/spython/main/parse/docker.py", line 40, in __init__
    super().__init__(recipe)
TypeError: super() takes at least 1 argument (0 given)
```

Step to reproduce:
```
git clone https://github.com/singularityhub/singularity-cli.git
cd singularity-cli
sudo python setup.py install
spython recipe Dockerfile
# same result with
spython recipe Singularity
```

I think a bug has been recently introduced.

Kind regards,
Rémy

**Comment by vsoch** [comment]
Also (and this probably doesn't make a difference) it looks like you are getting version 0.0.22 when the latest on pypi is 0.0.23! -->https://pypi.python.org/pypi/spython/0.0.23 This has happened to me before and usually it is because I didn't do pip install spython (as many times as needed) before to remove previous installs!

**Comment by vsoch** [comment]
okay see https://github.com/singularityhub/singularity-cli/pull/13 ! I'm going back to sleep (have to give a talk this morning) but I'll check on this before I leave!

**Comment by remyd1** [comment]
Perfect; the install using `pip3` solves this issue.

Thanks :+1:
