### ISSUE TITLE
Cache Singularity during testing

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-cli#126]
Now that we have Singularity versions somewhat more set, we can add a cache of Singularity itself to the testing. Also suggested by @Flamefire.

**Comment by vsoch** [comment]
@tschoonj  let's pick up conversation here from #140 - some questions:

 - should the cache happen here or with the orb? https://github.com/singularityhub/singularity-orb
 - in that different installs might conflict, how do we handle singularity paths?

**Comment by tschoonj** [comment]
I would install singularity in version dependent folders, and update the PATH according to the version requested by the user.

Don't know much about the orbs thing, only started using that yesterday after you're recommendation.

**Comment by vsoch** [comment]
ok, let me take a look at the orb and see if it's reasonable to add there. Having it there would mean that any user would benefit, which would be great.

**Comment by vsoch** [comment]
So instead of `/usr/local`, what would you use for the prefix?

**Comment by vsoch** [comment]
I'm failing spectacularly here https://github.com/singularityhub/singularity-orb/pull/8 in case you have any ideas. I can't seem to save a cache relevant to the version, and then extract it without permission errors. I tried adding a run block before that but it didn't seem to help.

**Comment by tschoonj** [comment]
Sorry, but that is very much uncharted territory for me... also the weekend has started for me and won't be back at work until Tuesday...

**Comment by vsoch** [comment]
No worries, I'm stubborn as an Ox, I'll figure it out :) Happy weekend!

**Comment by tschoonj** [comment]
I'm sure you will 👍 

Have a good weekend yourself and thanks again for all the help!

**Comment by vsoch** [comment]
Nope, not stubborn or good enough today it seems. I give up.

**Comment by vsoch** [comment]
hey @Flamefire I think you suggested adding a cache? I gave it a huge effort and couldn't get it to work - it will build successfully the first time given some location without write permission, but then when you extract the cache it fails the next time. If I added a change of permissions before creating the cache, and then creating the parent folder in a run block before extracting it, that didn't seem to work either. When I installed to /home/circleci that would technically work for the native builds, but of course break given install into a docker base. So - I'm out of ideas! See my attempts here https://github.com/singularityhub/singularity-orb/pull/8 and if you have any suggestions, it would be greatly appreciated.

**Comment by vsoch** [comment]
@Flamefire if you get bored some day, this recipe is (thankfully!) fully working, but it could use some beautification. 

https://github.com/singularityhub/singularity-orb/blob/3753c8b9edc08aa13b3d2e2e8830d28bcb34112d/src/orb.yml

I was mostly happy to get everything in working order :)
