### ISSUE TITLE
How to use a directory to build without actually changing directory ?

### ISSUE THREAD

**Issue by JayjeetAtGithub** [singularityhub/singularity-cli#135]
## What is your question?

Suppose, I have a directory `/home/jayjeet/jshint`  with some scripts and `Singularity` file.  I want these scripts to be inside my container. How can i build a container(`.simg`) in a different directory (my `$PWD`) without changing into the `/home/jayjeet/jshint` with singularity-cli ?

The issue that i am facing is that if i do `Client.build(recipe='/home/jayjeet/Singularity, image='jshint.simg', build_folder=os.getcwd())`, the build fails as it couldnt find the scripts while executing the statements `scripts/. /scripts` in the `%files%` section of my `Singularity` file.

**Comment by vsoch** [comment]
hey @JayjeetAtGithub, your scripts needs to be in the present (or a child) of your working directory - we call that the context. If I have this structure:

```
/home/jayjeet $
Singularity
     jshint/script1
     jshint/script2
```
You can build from `/home/jayjeet` and the scripts relative path is `jshint/script1` and `jshint/script2`.

If you are using older versions of Singularity, there can be issues with adding files (bugs) and so you can always resort to using a %setup section:

```
%setup

cp /home/jayjeet/jshint/* ${SINGULARITY_ROOTFS}/opt/
```
Note that in this section, the root of your container is $SINGULARITY_ROOTFS. And you can target paths on your system and do any sort of copy command.

Note that this isn't a Singularity Python issue, so I'm not sure why you posted here, but I'm glad to help.

**Comment by JayjeetAtGithub** [comment]
Thanks ! let me try out with `singularity 3.2`.
