### ISSUE TITLE
--writable option for execute/run not working in spython

### ISSUE THREAD

**Issue by JayjeetAtGithub** [singularityhub/singularity-cli#138]
## Expected Behavior

I have a sandbox `debian/` built from `debian.sif`.

```
>>> from spython.main import Client as c
>>> c.execute('debian', 'touch /file', writable=True, sudo=True)
{'message': "touch: cannot touch '/file': Read-only file system\n", 'return_code': 1}
```
but on doing the same natively from terminal,

```
sudo singularity exec --writable debian touch /file
```
it works and the file gets created.

## Actual Behavior
```
>>> c.execute('debian', 'touch /file', writable=True, sudo=True)
```
This step should work perfectly same like when done natively.

## Steps to Reproduce

```
sudo singularity build --sandbox debian/ docker://debian:buster-slim
```
Then do the above mentioned steps.
## Context

* Operating System: Ubuntu 16.04
* singularity version: 3.2.0
* spython version: 0.0.71
* python version: 3.7

## Failure Logs

```
{'message': "touch: cannot touch '/file': Read-only file system\n", 'return_code': 1}

[14]+  Stopped                 python
```

**Comment by vsoch** [comment]
Hey this definitely looks like a bug - is it okay if I fix it tomorrow morning (it's getting late on the east coast). Also - you wanted another argument added to the command (could you share that here too?) I'll do both at the same time.

**Comment by JayjeetAtGithub** [comment]
Sure .Thanks a lot @vsoch. I wanted the `--writable-tmpfs` option that is present in run and exec commands of 3.2.0. This would help me create a non persistent r/w temp fs, to be used during runtime.

**Comment by vsoch** [comment]
Did you do something special with overlaw for the first? I'm getting the same thing for the singularity on the command line and spython execute:

```bash
$ sudo singularity exec --writable busybox.sif touch /file
WARNING: While attempting to set up SIFOverlay: no SIF writable overlay partition found
touch: /file: Read-only file system
```

**Comment by vsoch** [comment]
Ah ok, building the sandbox works without that message, I'll use that to debug.

**Comment by vsoch** [comment]
Build:
```python
client.build('docker://debian:buster-slim', 'debian', sandbox=True, sudo=True) 
```
successful build of a sandbox:

```python
ls debian                                                                                               
bin/   dev/          etc/   lib/    media/  opt/   root/  sbin/         srv/  tmp/  var/
boot/  environment@  home/  lib64/  mnt/    proc/  run/   singularity@  sys/  usr/
```
Now issue touch command, two examples show getting just result, and getting return code too.

```python
$ client.execute('debian', 'touch /file', writable=True, sudo=True)                                       
 []

$ client.execute('debian', 'touch /file', writable=True, sudo=True, return_result=True)                   
$ {'message': [], 'return_code': 0}
```
and each of shell, exec, and run has added an options list (optional) where you can add `--writable-tmpfs`:

```python
client.execute('debian', 'touch /tmp/file',  options=['--writable-tmpfs'])
```
I'll open a PR for you to test shortly!

**Comment by JayjeetAtGithub** [comment]
Thanks ! I am checking it locally.
