### ISSUE TITLE
Converting singularity multi command `%post` directives translate into separate docker `RUN` commands

### ISSUE THREAD

**Issue by lyskov** [singularityhub/singularity-cli#142]
Dear developers, i noticed that if i try to convert singularity recipe into docker one when %post directive have multiple line the result is multiple docker `RUN` commands while expecting result should be a single `RUN` command. 

Here is a minimal example to reproduce this:
Singularity recipe:
```Bootstrap: docker
From: alpine
%post
    cd /root
    pwd
```

and `spython` conversion results is:
```FROM alpine
RUN cd /root
RUN pwd
```

Notice that there is two `RUN` command in output when expected result is a singe `RUN`

Thanks,

**Comment by vsoch** [comment]
That's really the only clean way to do it - we parse and look for continued lines (e.g., && \) but aside from that, it would be hugely error prone to try and clump an entire post into one line. I would be open to ideas if you have them and want to open a PR to review.

**Comment by vsoch** [comment]
The conversion tool is also not intended to be some gold standard, it handles most of the scut work and then the user would likely want to tweak the recipe to his or her liking.

**Comment by lyskov** [comment]
@vsoch thank you for clarifying this! I thought it would be great if converting from Docker to Singularity and back give the same file but i see how this could be problematic to implement.

quick, somewhat related question: - is `%post` behavior from example above an intended one (ie saving pwd and environment from one line to the next?

Thanks,

**Comment by vsoch** [comment]
It’s intended to convert each line to a RUN unless there is a continued line. What do you mean by environment? Was there a section in the example recipe left out above?

**Comment by lyskov** [comment]
Let me clarify: the issue with above example is that `cd /root` changed pwd and next lines used it. While the docker version no longer worked correctly because each new `RUN` command started with pwd equal to `/`. So my question was is `%post` behavior of propagating pwd is intended one or is this a bug?

**Comment by vsoch** [comment]
That is intended. Personally I’d say best practice (whether doing Singularity or Docker) is to, when you use a cd, put all relevant commands on one line. Then when you start a new line do a cd without a relative path, if necessary. Singularity doesn’t have a representation for WORKDIR so it is replaced with a cd, and in this case you’d wind up with a Singularity recipe that wouldn’t be ideal to convert them again back to Docker. But again, the tool isn’t really intended for this.

**Comment by lyskov** [comment]
Got it, - thank you for clarifying this @vsoch !
