### ISSUE TITLE
Get a 403 when using `singularity pull`

### ISSUE THREAD

**Issue by vladdoster** [singularityhub/singularity-cli#152]
## What is your question?
Why am I getting a 403 when I try to pull?

1. Am I being rate limited?
2. Is it because I am on an VPN?

![pic-selected-200420-1649-47](https://user-images.githubusercontent.com/10052309/79803182-1fe0a280-8327-11ea-8523-7e76d8ffd035.png)

[write your question here, and answer the prompts below]

 - [x] I found the documentation at https://singularityhub.github.io/singularity-cli/
 - [x] The documentation does not answer my question

If the documentation doesn't answer your question, where do you think it would be appropriate to add (i.e., where did you go looking for it?)

Document response codes? Why am I forbidden?

**Comment by vladdoster** [comment]
Am I being rate limited?

**Comment by vsoch** [comment]
@vladdoster the repository here is for singularity-cli, which is the Python wrapper for Singularity. The command that you are showing is for singularity proper, which is at https://github.com/sylabs/singularity.

But I can definitely answer your question anyway - because I run singularity hub - the rate limit isn't exhausted, and I can in fact pull that image:

```
$ singularity pull shub://vsoch/singularity-images
INFO:    Downloading shub image
```
I think you should probably open an issue on the sylabs/singularity board, because this seems to be related to your specific install / pull of the container.

**Comment by vladdoster** [comment]
@vsoch It does work sometimes. I could pull it normally for a while, and then it went on the fritz.

I just tried again and I had no issues. Odd.

![pic-selected-200420-1702-36](https://user-images.githubusercontent.com/10052309/79804024-c6797300-8328-11ea-9ab1-a2791ba9acb7.png)

**Comment by vsoch** [comment]
Ah okay it could be rate limiting then - you aren't totally blocked, but if you pull too frequently you are blocked for a little bit :) Sorry for the trouble - the reasons for adding these "features" back last summer were extremely important for the longevity of Singularity Hub - imagine a really big container, and then imagine that someone (maliciously or other) pulls it thousands of times on a huge cluster. The egress charges for that... are not sustainable!

Glad that it's working!

**Comment by vladdoster** [comment]
Gotcha. Does it rate limit for said image I am trying to download or for whole domain?

**Comment by vsoch** [comment]
The view rate limits are for each page, so you shouldn't regularly refresh a page either. There is some detail here, albeit it's probably not perfect. https://singularityhub.github.io/singularityhub-docs/docs/regulatory/limits

**Comment by vladdoster** [comment]
@vsoch you are the best :fireworks:.
