### ISSUE TITLE
How to override bot to only output `Error` or `Abort` logs

### ISSUE THREAD

**Issue by vladdoster** [singularityhub/singularity-cli#153]
## What is your question?
I am having trouble overriding the bot logger. Ideally, I would only want to output `ERROR` messages unless specified otherwise. 

I think I chased it down to here: https://github.com/singularityhub/singularity-cli/blob/e325c628f680881a1eea9a62307cf1b3c1c85a98/spython/main/base/__init__.py#L27

I tried sub-classing `client`. Subclass `client` and then override the `__init__(): method to call `set_verbosity` with my desired `LOG_LEVEL`? I also tried setting env variables to `SINGULARITY_MESSAGELEVEL` & `MESSAGELEVEL` but didnt seem to get anywhere. I am not too sure how to proceed. Any ideas on how to approach this? I am all ears!

Also I don't quite understand how the `Client.build(stream=True)` allows it to error or else it will just proceed. How does returning the generator stream allow it to error? Is it not run in `bg` vs `fg` when streamed thus allows to error in same python process? 

 - [x] I found the documentation at https://singularityhub.github.io/singularity-cli/
 - [x] The documentation does not answer my question

If the documentation doesn't answer your question, where do you think it would be appropriate to add (i.e., where did you go looking for it?)

**Comment by vsoch** [comment]
Can you give me some basic commands to reproduce your issue? Then I can use that to (try) and show you how to set it.

**Comment by vladdoster** [comment]
So a user submits arguments via argparse, and it instantiates a subclass which inherits from BaseHandler. Ideally the --verbose flag (True/False) would allow me to swap between no output logged and being able to change between whatever we desire (probably the default logging level). It then uses Client.build() to try and build said URI or file path the user provides. 

```
    try:
        os.environ["SINGULARITY_MESSAGELEVEL"]="ERROR"
        os.environ["MESSAGELEVEL"]="ERROR"
        user = os.getenv("USER")
        if args.status:
            sys.exit("--status is not implemented yet.")
        if args.img_fpath and args.img_uri:
            sys.exit("Can not use --image-path and --image-uri at the same time")
        if args.img_fpath:
            print(FileHandler(
                distribution=args.distribution,
                force=args.force,
                user=user,
                verbose=args.verbose,
                fpath=args.img_fpath[0],
            ).process())
        elif args.img_uri:
            UriHandler(
                distribution=args.distribution,
                force=args.force,
                user=user,
                verbose=args.verbose,
                uri=args.img_uri[0],
            ).process()
        else:
            sys.exit("Need to supply either --image-path or --image-uri")
    except KeyboardInterrupt:
        print("interrupt received, cancelling submission…")
    finally:
        pass

class BaseHandler(object):
    def __init__(self, distribution, force, user, verbose, fpath=None, uri=None):
        # self.bot = ModifiedSingularityMessage()
        self.distribution = distribution
        self.force = force
        self.fpath = fpath
        self.uri = uri
        self.user = user
        self.verbose = verbose
        self.def_dir = os.path.join(os.path.curdir, "image_definitions")
        self.builds_dir = os.path.join(os.path.curdir, "container_builds")
        # process
        self.verify()
        self.gen_details()

    def __str__(self):
        pp = pprint.PrettyPrinter(indent=4)
        pp.pprint(self.__dict__)

    def generate_details(self):
        raise NotImplementedError

    def verify(self):
        raise NotImplementedError

    def process(self):
        raise NotImplementedError


class FileHandler(BaseHandler):
    def __init__(self, distribution, force, user, verbose, fpath):
        self.dockerfile = False
        super().__init__(distribution, force, user, verbose, fpath)

    def verify(self):
        if not os.path.exists(self.fpath):
            sys.exit("File path does not point to a valid file")
        return True

    def generate_details(self):
        self.fname, self.fext = os.path.splitext(os.path.split(self.fpath)[1])
        self.img_def, self.img_sif = (
            self.user + "_" + self.fname.lower() + ".def",
            self.user + "_" + self.fname.lower(),
        )
        if "dockerfile" in self.img_def:
            self.dockerfile = True
        elif self.fext not in [".def", ".simg", ".sif"]:
            sys.exit("File needs to end in .def, .simg, or .sif")
        return True

    def process(self):
        try:
            if self.dockerfile:
                DockerParser = get_parser("docker")
                parser = DockerParser(self.fpath)
                SingularityWriter = get_writer("singularity")
                writer = SingularityWriter(parser.recipe)
                with open(
                        file=os.path.join(self.def_dir, self.img_def), mode="w+"
                ) as file:
                    file.write(writer.convert())
            else:
                shutil.copy(self.fpath, os.path.join(self.def_dir, self.img_def))
            _, builder = Client.build(
                build_folder=self.builds_dir,
                recipe=os.path.join(self.def_dir, self.img_def),
                image=self.img_sif,
                force=True,
                ext=".sif",
                sudo=True,
                stream=True,
                sandbox=False,
                quiet=True,
            )
            # without this, the build will never SystemExit
            for line in builder:
                print(line, end='')
            return True
        except SystemExit:
            sys.exit("Check that %s syntax is correct" % self.fname)
```

And without this line the Build command wont SystemExit or throw any exception. which is why I have it.
```
for line in builder:
    print(line, end='')
```

**Comment by vsoch** [comment]
I think the issue is that you are running spython from inside python, and then executing to the command line to run singularity. The environment variables (to be honored by the client) need to be exported to the caller first. If you are using it programatically like this, I suggest just setting quiet to True: https://github.com/singularityhub/singularity-cli/blob/master/spython/main/build.py#L28. Have you tried that?

**Comment by vsoch** [comment]
You can do a print here https://github.com/singularityhub/singularity-cli/blob/master/spython/logger/message.py#L286 to see if it's discovered.

**Comment by vladdoster** [comment]
It does seem to be getting caught. But I still get `INFO`

![pic-selected-200421-1648-50](https://user-images.githubusercontent.com/10052309/79917399-0e170200-83f0-11ea-8061-4885a4aaea0e.png)

**Comment by vladdoster** [comment]
Even when I assign `level="ERROR" I still get `WARNING` and `INFO` logs? Maybe I am mistaking these logs as singularity logs?

**Comment by vsoch** [comment]
Ohh thank you for showing me that! So that is an output message from Singularity, not Singularity python. You would need to pass in a verbosity level to the Singularity client via build options. Let me know if that doesn’t make sense.

**Comment by vladdoster** [comment]
ahh okay. I will do that then! Thank you so much!!!

**Comment by vladdoster** [comment]
Do you happen to know which flags .mconfig?

**Comment by vsoch** [comment]
Oh sorry, so I mean input arguments to Client.build(), not the Singularity build proper. So if you do `singularity --help` you can see options for verbosity:

```
Linux container platform optimized for High Performance Computing (HPC) and
Enterprise Performance Computing (EPC)

Usage:
  singularity [global options...]

Description:
  Singularity containers provide an application virtualization layer enabling
  mobility of compute via both application and environment portability. With
  Singularity one is capable of building a root file system that runs on any 
  other Linux system where Singularity is installed.

Options:
  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/usr/local/etc/singularity/singularity.conf")
  -d, --debug           print debugging information (highest verbosity)
  -h, --help            help for singularity
      --nocolor         print without color output (default False)
  -q, --quiet           suppress normal output
  -s, --silent          only print errors
  -v, --verbose         print additional information
      --version         version for singularity
```
And you would want to pass this to Client.build(). But actually, the options that go into there are passed to build (and not to singularity)

https://github.com/singularityhub/singularity-cli/blob/master/spython/main/build.py#L14

I can open a PR for you to add a `singularity_options`  parameter that you could add something like:

```
Client.build(..., singularity_options=["--silent"])
```

Would that work? What I'd suggest you do is try the different options that the singularity (base client) can provide, and if you can find how to control the logging level, please share here with me. If you can't, then open an issue on sylabs/singularity and ask how they should go about doing this. We will expose something here that makes it possible. Sound good?


But what I'm referring to is the command line use,

**Comment by vladdoster** [comment]
Ah, thank you! That makes sense. I can definitely do that. I will report back!

**Comment by vladdoster** [comment]
Oh yes, the `--silent option` is ideal! So nice!

**Comment by vsoch** [comment]
okay, let me get in a PR asap so you can test.

**Comment by vladdoster** [comment]
So it seems that from most logging to least logging is:
`--debug` - Special `DEBUG` messages with what look to be memory addresses + `WARNING` + `INFO`
`--verbose` - Special `VERBOSE` messages which give some insight, In a build, I got 1 `VERBOSE` message + `WARNING` + `INFO`
`quiet` - Only `WARNING`
`--silent` - No output unless error

**Comment by vsoch** [comment]
I think --debug and --quiet are passed on from singularity python to singularity, but not the others. Opening up a PR for you to test soon.

**Comment by vsoch** [comment]
Could you please test https://github.com/singularityhub/singularity-cli/pull/157?
