### ISSUE TITLE
Pass stdin for spython `execute` calls

### ISSUE THREAD

**Issue by hans** [singularityhub/singularity-cli#161]
Hi, I'd like to execute commands in Singularity containers piping a stream through stdin. I don't believe this is currently possible in `spython` — do you have any plans to support it?

Thanks for the great tool!

**Comment by vsoch** [comment]
Can you show me a dummy (Singularity container only) example, and an example for how you'd want that to work with spython? It seems like something we could support, but I want to make sure I understand what you have in mind.

**Comment by hans** [comment]
Hi, thanks for the quick response! Here's what I want to reproduce on the shell, concretely:

```
$ echo "This is a test" | singularity exec shub://vsoch/hello-world cat /dev/stdin
This is a test
```

For my purposes, the ideal API would just take an optional `stdin` kwarg, which is a text or raw IO stream. I've implemented something like this in a hack around the current `spython` setup [in my current code](https://github.com/cpllab/lm-zoo/blob/feature/singularity/lm_zoo/backends/singularity.py#L45).

The Docker Python API's model works a little differently — you pass a flag `stdin_open`, which then allows you to write to a socket stored in the method's return value. I grant this is the more general solution, but probably harder to make work. In any case, allowing us to pipe to stdin by some method would be nice!

**Comment by vsoch** [comment]
This seems like a _very_ specific use case, and in that you can capture the stdin however you like and then pass it as the command, it feels out of scope for Singularity Python. But your implementation is great - what about instead adding this client as an example to the docs, so that anyone that wants some custom stdin/stdout can start with it?
