### ISSUE TITLE
Singularity doesn't support multistage builds

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-cli#163]
Reported on the Singularity list:

https://groups.google.com/a/lbl.gov/forum/?utm_medium=email&utm_source=footer#!msg/singularity/n9j40CVykk4/ouddGVkxBQAJ

Singularity does not support multistage builds, so we need to check for these lines and not add them. The warning can also be cleaned up to be shown in one line and not two.

**Comment by dctrud** [comment]
Singuarity does have multi-stage builds: https://sylabs.io/guides/3.5/user-guide/definition_files.html#multi-stage-builds

There have been changes to the copying semantics (it now matches Docker better), but this has been in place since 3.2 or 3.3 - I forget, but should be in the CHANGELOG.

**Comment by vsoch** [comment]
Thank you! I'll get something working here.
