### ISSUE TITLE
Errors when parsing singularity definitions with comments before bootstrap line

### ISSUE THREAD

**Issue by StopMotionCuber** [singularityhub/singularity-cli#180]
## Expected Behavior

When parsing a singularity definition _with_ comments before the bootstrap line, the file should be successfully parsed

## Actual Behavior

The parsing throws an `UnboundLocalError: local variable 'comments' referenced before assignment`

## Steps to Reproduce

1. Create a definition file with the following content:
```
# Minimal Example - This comment line is important for reproduction purposes

Bootstrap: docker
From: ubuntu:16.04
```
2. Start a python interpreter in that directory, with `spython` installed
3. Execute
```python
from spython.main.parse.parsers import SingularityParser
SingularityParser("minimal.def")
```
in that directory

## Context

* Operating System: Arch Linux
* singularity version: not installed
* spython version: 0.1.15
* python version: 3.9.7

## Failure Logs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[redacted]/venv/lib/python3.9/site-packages/spython/main/parse/parsers/singularity.py", line 30, in __init__
    super(SingularityParser, self).__init__(filename, load)
  File "[redacted]/venv/lib/python3.9/site-packages/spython/main/parse/parsers/base.py", line 56, in __init__
    self.parse()
  File "[redacted]/venv/lib/python3.9/site-packages/spython/main/parse/parsers/singularity.py", line 41, in parse
    self.load_recipe()
  File "[redacted]/venv/lib/python3.9/site-packages/spython/main/parse/parsers/singularity.py", line 333, in load_recipe
    elif stripped.startswith("#") and stripped not in comments:
UnboundLocalError: local variable 'comments' referenced before assignment
```
## Possible Fix

https://github.com/singularityhub/singularity-cli/blob/master/spython/main/parse/parsers/singularity.py#L318
That `comments` definition could to be repeated somewhere above

**Comment by vsoch** [comment]
Oh this is easy to fix! I'll get a PR in for you at the end of the work day. Thanks for pointing out the issue!

**Comment by vsoch** [comment]
@StopMotionCuber would you care to review? https://github.com/singularityhub/singularity-cli/pull/181
