### ISSUE TITLE
Copying file to $WORKDIR doesn't match with the logic in Docker

### ISSUE THREAD

**Issue by tanlin2013** [singularityhub/singularity-cli#184]
## Dockerfile
In the original Dockerfile I have

```
FROM intel/oneapi-basekit
FROM intel/oneapi-hpckit

ARG WORKDIR=/home
WORKDIR $WORKDIR

COPY . $WORKDIR

RUN tar -xzvf myzippedfile.tar.gz
```

## Singularity.def

By taking Dockerfile as recipe
```
spython recipe Dockerfile &> Singularity.def
```
it yields
```
Bootstrap: docker
From: intel/oneapi-hpckit
Stage: spython-base

%files
. $WORKDIR
%post

WORKDIR=/home
cd $WORKDIR


tar -xzvf myzippedfile.tar.gz
```

## Expected Behaviors
1. There are 2 base images (the `From` statement) in Dockerfile. But one is missing in Singularity.def ?
2. `tar` can't find `myzippedfile.tar.gz` in `$WORKDIR`
3. unnecassary spaces appear below `%post`, though this is not that important.

## Failure Logs
While performing build cmd
```
singularity build --fakeroot myimage.sif Singularity.def
```
I encounter this error

```
2021/09/30 23:27:13  info unpack layer: sha256:e3effb4ec06f77024a9a96f45fa68310e9978bfcfcabadb1689d366d6ce52842
INFO:    Copying . to /tmp/build-temp-296684841/rootfs/$WORKDIR
INFO:    Running post scriptlet
+ WORKDIR=/home
+ cd /home
+ tar -xzvf myzippedfile.tar.gz
tar (child): myzippedfile.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
FATAL:   While performing build: while running engine: exit status 2
```
So it appears like singularity copies the file into a tmp building folder, rather than `$WORKDIR` I expected.

**Comment by vsoch** [comment]
We don’t currently support multistage builds, but I’d be happy to review a PR to add them. For the WORKDIR this also isn’t supported by Singularity so it’s best a hack.

**Comment by tanlin2013** [comment]
Thanks you vsoch. Ok, I will try the way as you suggested.
