### ISSUE TITLE
STOPSIGNAL not handled in spython recipe

### ISSUE THREAD

**Issue by ksyx** [singularityhub/singularity-cli#203]
## Expected Behavior
[`STOPSINGAL`](https://docs.docker.com/engine/reference/builder/#stopsignal) in original `Dockerfile` should be commented and translated to corresponding Singularity definition line if needed.

## Actual Behavior

The line seemed to be recognized as a general command.

## Steps to Reproduce

With `STOPSIGNAL SIGINT` in `Dockerfile`, run `spython recipe Dockerfile` and it appears uncommented in the `.def` file.

## Context

* Operating System: Ubuntu 20.04.4 LTS Linux 5.4.0-125-generic
* singularity version: 3.8.5
* spython version: 0.2.13
* python version: 3.9.12

## Failure Logs
N/A

## Possible Fix
Add a handler for STOPSIGNAL function in `parse/parsers/docker.py`

**Comment by vsoch** [comment]
Does Singularity have an equivalent command?

**Comment by ksyx** [comment]
I was not aware of this so it could simply be commented out when generating I think?

**Comment by vsoch** [comment]
@ksyx there could be many directives (akin to this) that we don't know how to handle - is there a reason you don't want to just manually comment it? The recipe generator is intended as a good first shot, and we can't promise perfection. If there is a small list of these directives that are reliably / regularly used that you want to add (and ensure they are commented) that would work.

**Comment by ksyx** [comment]
Yeah making it a start point makes sense for me and I have not a very strong need of using this regularly, just noted this fact. Thanks!

**Comment by vsoch** [comment]
Oh, but I'd be happy to add this for you - it does look like a known docker directive! Give me a few mins. Sorry I didn't mean to be dismissive!

**Comment by vsoch** [comment]
okay please check out https://github.com/singularityhub/singularity-cli/pull/204! It's fairly simple and just comments the line. I looked up here https://docs.docker.com/engine/reference/builder/ and (at quick glance) I don't see others like it (but we could theoretically add them too).

**Comment by ksyx** [comment]
This looked awesome and would be helpful, thank you!

**Comment by vsoch** [comment]
Thank you @ksyx ! https://pypi.org/project/spython/0.2.14/
