### ISSUE TITLE
`spython recipe` vs. `singularity build`

### ISSUE THREAD

**Issue by radusuciu** [singularityhub/singularity-cli#218]
Hi, this question crosses repository boundaries so I wasn't sure if this is the best place to ask -- please feel free to close, though I'd appreciate any pointers.

**Context**
I'm working on a project that uses GitHub Actions to build Docker images. Currently, Singularity images are also made available and are built from a `.def` that is generated on the fly from the corresponding `Dockerfile` using `spython`.

**My question**
When going from docker -> singularity, would you advise reaching for `spython recipe`, or is `singularity build docker:// ...` preferrable?

Thank you for your time!

**Comment by vsoch** [comment]
I would suggest building just docker, and then advising your users to pull down to singularity, e.g.,

```bash
singularity pull docker://<uri>
```

**Comment by radusuciu** [comment]
This is for a PR (https://github.com/OpenMS/OpenMS/pull/7303) for an already widely used project and I'd like to avoid a change that potentially breaks things for end-users.

I guess my underlying question was: is current Singularity support for building docker images sufficiently advanced that `spython recipe` shouldn't be necessary?

**Comment by vsoch** [comment]
yes.

**Comment by radusuciu** [comment]
Thank you very much!
