### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [singularityhub/singularity-cli#220]
## Expected Behavior

Able to download the source from GitHub.

## Actual Behavior

Source is not tagged. Latest release is only available on [PyPI](https://pypi.org/project/spython/#history).

## Steps to Reproduce

Check https://github.com/singularityhub/singularity-cli/tags.

## Context

Otherwise all distributions which were shipping this Python module and were using the GitHub releases need to change their description to build `spython` in the latest release.

## Failure Logs

na

## Possible Fix

Tag the source please. Thanks

**Comment by vsoch** [comment]
You can find our releases on pypi: https://pypi.org/project/singularity-cli/#history

**Comment by vsoch** [comment]
And releases are here: https://github.com/singularityhub/singularity-cli/releases What's the issue?

**Comment by fabaff** [comment]
Mismatch between PyPI releases and tags.

- PyPI: 0.3.13, https://pypi.org/project/spython/#history
- GitHub: latest tag 0.3.12 (https://github.com/singularityhub/singularity-cli/tags while the latest release is also 0.3.12)

Nixpkgs uses GItHub as the source for building their package (I haven't check other distributions), thus the tag is used to determine what to download.

**Comment by vsoch** [comment]
I think it’s a mistake - the two versions are identical. So the GitHub one should be OK.
