### ISSUE TITLE
Client.execute hangs my python code

### ISSUE THREAD

**Issue by hawkspar** [singularityhub/singularity-cli#221]
## Use case

I need to interact back and forth between a python code outside a singularity container and an application inside said container.

To do that I use ```singularity-cli``` to create an instance and I want to use it to run the application in the background of the main script. This main script has to proceed for the application in the container to continue to run.

## Code snippet

My code looks something like :

```python
from spython.main import Client
import json

container=Client.instance("myimage.sif",name="dud",options=['-B','./in:/home/in','./out:/home/out'])

Client.execute(container,['myapp','/home/in/myargs'],writable=True)

while True:
    try:
        with open('./out/res.txt','r').readlines() as output:
            return json.load(output)
    except FileNotFoundError: continue
```

I know that there are more elegant ways to exchange data with the container than using temporary files, but that's secondary right now.

## Expected Behavior

I expect ```Client.execute``` to run in the background, not blocking the interpreter, which would allow me to read the singularity ```myapp``` results as soon as they are available.

## Actual Behavior

I'm sure my code hangs on the ```Client.execute``` line.

## Context

* singularity version: 4.1.4-1
* spython version: 0.3.13
* python version: 3.9.18

## Possible Fix

This looks related to _al3x609_'s problem, one of the proposed fix was using exec...

**Comment by vsoch** [comment]
Can you give me a dummy example I could run to reproduce the issue you are having? I don't think a client.execute would logically (by default) be running in the background. I think it's more likely you'd set stream to True and then get the lines returned as they are generated.

**Comment by hawkspar** [comment]
Thank you for your speedy response.

It turns out to accomplish what I needed I just had to skip the
```Client.instance``` part and directly provide an image to ```exec```
instead of an instance. Then it runs in the background as expected.

This is slightly suboptimal as it leads to multiple instances being
generated in the final code. I could not find a ```stream``` option either
in ```singularity-cli``` or in Singularity itself.

I'm sorry I can't make a clean test case right now. It should be easy to
test with a sleep in the container and a print outside that exec causes the
code to hang.

If you have a way to run several execs on the same instance and/or to
communicate small amounts of data fast with the container more efficiently
than through files, I'm all ears.

**Comment by vsoch** [comment]
execute has stream (boolean) as an argument.

**Comment by hawkspar** [comment]
It doesn't show when doing ```help(spython.main.Client.execute)``` for my
version of ```spython```.

**Comment by vsoch** [comment]
These are the options available to you:

https://github.com/singularityhub/singularity-cli/blob/2b222339382e92f9b93357b3bc81d6558e4efdcd/spython/main/execute.py#L14-L31

**Comment by hawkspar** [comment]
It's still unclear to me why it works with ```exec``` and not the snipper I provided, but the problem can be considered solved.

Thank you for the help.
