### ISSUE TITLE
Add support for other bootstrap types in recipe conversion

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-cli#38]
- localimage
 - shub

Any others?

**Comment by shahzebsiddiqui** [comment]
So easybuild supports localimage as bootstrap so there would be recipe files as follows

```
[siddis14@amrndhl1295 ebimages]$ cat Singularity.zlib-1.2.11

Bootstrap: localimage
From: /lustre/workspace/home/hpcswbuild/eb_images/Bison-3.0.4.img

%post


# upgrade easybuild package automatically to latest version
pip install -U easybuild

# change to 'easybuild' user
su - easybuild

eb zlib-1.2.11.eb --robot --installpath=/app/ --prefix=/scratch --tmpdir=/scratch/tmp

# exit from 'easybuild' user
exit

# cleanup
rm -rf /scratch/tmp/* /scratch/build /scratch/sources /scratch/ebfiles_repo

%runscript
eval "$@"

%environment
source /etc/profile
module use /app/modules/all
module load zlib/1.2.11

%labels

```

The idea is to convert ``Singularity.zlib-1.211`` to dockerfile and have easybuild build the container using the generated docker file. 

I don't know about converting to shub. If recipe is a Singularity recipe and the bootstrap is ``localimage`` or ``docker`` then having ``shub`` as the bootstrap imply container to be built in SingularityHub which may or may not work depending on the application. 

I guess it makes sense to have conversion from docker to singularity recipe I have not tried that yet. Let me give that a try

**Comment by vsoch** [comment]
Closing because this doesn't make sense :)
