### ISSUE TITLE
Add Instance control to Singularity Python

### ISSUE THREAD

**Issue by wkpalan** [singularityhub/singularity-cli#42]
The following command is what I use for starting an instance and running a command, especially because I am using MySql service. 
```
singularity instance.start \ 
    --bind $PWD/GOMAP-data/mysql/lib:/var/lib/mysql \
    --bind $PWD/GOMAP-data/mysql/log:/var/log/mysql \ 
    --bind $PWD/GOMAP-container:/opt/GOMAP \ 
    --bind $PWD/GOMAP-data:/opt/GOMAP/data \ 
    --bind $PWD:/workdir \ 
    -W $PWD/tmp \ 
    $img_loc $instance_name && \ 
singularity run \ instance://$instance_name $@
singularity instance.stop $instance_name
```

Would it be possible to add the instance.* commands to Singularity Python so that starting and stopping instances with proper bindings could be called from python. This allows for reading new config for binding directories from json or yaml file.

**Comment by vsoch** [comment]
Per discussion in gitter, yes I definitely think so! I'll get started on this soon and hopefully have something for you to test by the weekend.

**Comment by wkpalan** [comment]
I agree. I think having control functions on the instance object itself makes more sense opposed to importing the spython client and running the instance. 

This way multiple instances can be started and followed through within the same script as variables opposed to saving the name in a separate list.

I'll let you know if I think of anything else that might make sense.

**Comment by vsoch** [comment]
@wkpalan I still need to write tests (and run them) but there is a PDF attached here if you want to see how things will work! --> https://github.com/singularityhub/singularity-cli/pull/43

I'll try to make some more time this weekend for those tests, and I'll let you know when it's ready for your testing!

**Comment by wkpalan** [comment]
Thanks for the heads up.

**Comment by vsoch** [comment]
I think you are likely pulling to a `SINGULARITY_CACHEDIR` that is in your home (that is filled up on the resource). Try exporting it to be somewhere with lots of room:

```bash
export SINGULARITY_CACHEDIR=$SCRATCH/.singularity
```
and trying again!

**Comment by wkpalan** [comment]
It looks like even after that it hangs. Let me see if it improves after I install the latest version from master

**Comment by vsoch** [comment]
Note that this was also tested (and developed) on singularity 2.5.0. If it doesnt work again please provide:

 - the version of singularity and environment
 - an example (and output / result) of running the commands on the local host
 - the same commands run with spython, and the result

This will let me debug the issue. Thanks!

**Comment by vsoch** [comment]
A

**Comment by wkpalan** [comment]
Script #1
```
from spython.main import Client
Client.instance(image="shub://jekriske/lolcow:lowfat",name="lolcow")
Client.run()
```

Script #2
```
from spython.main import Client
Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
Client.instance(image="lolcow.simg",name="lolcow")
Client.run()
```

**Comment by wkpalan** [comment]
Singularity version - 2.5.2-feature-squashbuild-secbuild-2.5.0.bad17afe

```
singularity pull -n lolcow.simg shub://jekriske/lolcow:lowfat
singularity run lolcow.simg
singularity instance.start lolcow.simg lolcow
```

```
from spython.main import Client
Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
Client.instance(image="lolcow.simg",name="lolcow")
Client.run()
```

**Comment by vsoch** [comment]
You aren't running the instance - you are creating a client, then creating an instance (but not getting the return uri from it) and then running the client (that doesn't have anything associated.) Again, don't forget the return argument! Remember, there are guides that walk you through this. -->
https://singularityhub.github.io/singularity-cli/commands-instances

For example, from reading, I would try this....

```bash
from spython.main import Client
myinstance = Client.instance(image="shub://jekriske/lolcow:lowfat",name="lolcow")
print(myinstance)
result = Client.run(myinstance)
```

**Comment by vsoch** [comment]
As I asked above, please run the command with LOCAL singularity and send me the output first. I think you might need to read things / instructions / docs better :) Is english your native languag?

**Comment by vsoch** [comment]
Thanks for the fixes btw!

**Comment by wkpalan** [comment]
English is not my native language, but that doesn't seem to have impacted my ability to copy paste the lines from the comment above.

**Comment by vsoch** [comment]
ok no worries! Just for fyi, I've been working this evening to add automated builds (and testing of them) to the repos here so we can be sure the Docker containers build too :)
