### ISSUE TITLE
Dockerfile conversion example followup

### ISSUE THREAD

**Issue by bbarker** [singularityhub/singularity-cli#44]
This is a placeholder while still working on the issue, I will add more items later, as well as a full example. This isn't meant to be exhaustive, but follows a somewhat complex (though not very long) Dockerfile to Singularity recipe conversion example.

- [ ] Dockerfile `USER` directives should be removed and a warning emitted (I assume, or is this possible in Singularity?).
- [ ] Quotes are currently not expanded as in a shell, so having something like this under `%files` will not work: `"./${DISTRO_INSTALL_CMDS}" /tmp" - in this particular case, just removing the double quotes will work.
- [ ] If destination directories do not exist under `%files`, a `mkdir -p` may need to be added under `%setup`.
- [ ] changes to `$HOME` should issue a warning. This is typically not going to be the same sort of thing in Singularity since by default `HOME` is bind mounted to the actual user's home directory, potentially resulting in damage tot he user's system. However, since `$HOME` doesn't exist during the build, I'm not sure what the exact behavior would be, but probably not the expected behavior in any case. Ideally, one might be able to specifying in the Singularity recipe to use a non-bind mounted $HOME, though I'm not sure this is possible.
- [ ] environment variables defined with `ENV` should be replicated in both `%environment` and `%post` (currently only done in the former), see Docker docs [for details](https://docs.docker.com/engine/reference/builder/#env), but in short, `ENV` makes variables available at build time and run time. So far I haven't noticed if there is a way to do this in a non-duplicated fashion in a Singularity recipe. The user can then refine their Singularity recipe if desired for the additional customization allowed by Singularity, but this is the model that should be followed by default for Docker compat.

**Comment by vsoch** [comment]
@bbarker this is great! Would you like me to start working on these, or pause until you've finished up?

**Comment by bbarkerro** [comment]
@vsoch sure, I don't think it hurts to start working on them if you want (as long as what I said makes sense).

**Comment by vsoch** [comment]
ok, great! I'll get started on these a little later today, and ping you with any questions.

**Comment by vsoch** [comment]
I'm going to break into separate issues to easier address.

**Comment by vsoch** [comment]
@bbarker for the second I'm not sure how is best to address because we don't want to really expand quotes (the next builder of the recipe won't have the hardcoded path). Are you thinking if we simply search for escaped quotes (and remove them) this will be a good first shot?

**Comment by vsoch** [comment]
And could you provide an example with 

 - 1. the current input and output (with the quotes) and 
 - 2. the expected output

**Comment by vsoch** [comment]
@bbarker the last one should already add the environment to post and to environment, see the environmnet section here:

```bash
    def _env(self, line):
        '''env will parse a line that beings with ENV, indicative of one or
           more environment variables.
 
           Parameters
           ==========
           line: the line from the recipe file to parse for ADD
   
        '''
        line = self._setup('ENV', line)

        # Extract environment (list) from the line
        environ = parse_env(line)

        # Add to global environment, run during install
        self.install += environ

        # Also define for global environment
        self.environ += environ
```
For example, a simple Dockerfile:

```
FROM continuumio/miniconda3

ENV VARIABLENAME VALUE
```
convert

```
spython recipe Dockerfile
```
The variable is defined in %post and in the %environment section:

```
Bootstrap: docker
From: continuumio/miniconda3
%post

VARIABLENAME=VALUE
%environment
export VARIABLENAME=VALUE
%runscript
exec /bin/bash "$@"
```
Could you give me an example of what is not working, and also the version of spython if you think it's relevant?

**Comment by vsoch** [comment]
And with respect to changes to $HOME, I think it's expected that the $HOME during build is /root, for both builds. Can you give an example of a hairy situation so I can better understand?

**Comment by bbarker** [comment]
Here is a working (though perhaps not perfect) [Singularity template file](https://github.com/federatedcloud/NixTemplates/blob/3a2d8013299094cff1339330f836ba309ace4c01/Base/InSingularity) that is passed to `envsubst` from GNU gettext for better environment variable expansion.

For comparison (though perhaps not exact, a few very minor things may have changed, like switching from /bin/bash to /bin/sh), you can see the automatically output Singularity recipe posted in this thread: https://github.com/singularityhub/singularity-cli/issues/39

The changes are quite substantial and I don't know how much is reasonable to address. At least the output file provided a helpful starting point to a singularity newbie.

**Comment by geektortoise** [comment]
Hello, 
An example for the third point 

Dockerfile : 

FROM XXX:latest
RUN mkdir -p /app
ADD run.py /app/run.py
ENTRYPOINT ["python", "/app/run.py"]

Result after Singularity recipe (v 0.0.49)

Bootstrap: docker
From: XXX:latest
%files
run.py /app/run.py
%post
mkdir -p /app

%runscript
exec /bin/bash "$@"


So, it doesn't work because files are copied before the post commands execution.

Working recipe file:

Bootstrap: docker
From: XXX:latest
%setup
mkdir -p ${SINGULARITY_ROOTFS}/app/

%files
run.py /app/run.py

%runscript
exec /bin/bash "$@"


Have a nive day !

**Comment by vsoch** [comment]
Do you have a suggestion for how this could be fixed? There is no way of knowing that any particular RUN command to create a directory should be in setup.

**Comment by vsoch** [comment]
I would suggest opening an issue on the singularity board and suggesting some kind of specification for pre/post files. As an alternative, you can just change your script above:

```
FROM XXX:latest
ADD run.py /run.py
ENTRYPOINT ["python", "/run.py"]
```
or

```
FROM XXX:latest
ADD run.py /run.py
RUN mkdir -p /app && \
    mv /run.py /app
ENTRYPOINT ["python", "/run.py"]
```

**Comment by geektortoise** [comment]
The suggestion of bbarker is not possible ?
"If destination directories do not exist under %files, a mkdir -p may need to be added under %setup"

Basically, read all instructions into Dockerfile that will be converted into the %files sections (i guess the only the ADD and COPY commands)
For each instruction 
[ADD/COPY] origin dest
check if the dest folder exist, if not, add the mkdir -p ${SINGULARITY_ROOTFS}/dest_dir into the setup section

But I don't know if it is possible during the conversion process. :/

And ... sorry for the newbie question : what and where is the "singularity board" ? ^^
