### ISSUE TITLE
Using absolute path for images seems to create an issue

### ISSUE THREAD

**Issue by wkpalan** [singularityhub/singularity-cli#49]
Using absolute path for images when loading them creates and issue for running them later. 

Could the get_uri or remove_uri functions from `singularity-cli/spython/image/__init__.py` could be causing this?

I have created a blame comment on the relevant lines to let you know where I think the issue might be. #

**Comment by vsoch** [comment]
Could you please give a command (here) to reproduce the issue? I'm having trouble following the blame view. You also commented on a commit that didn't pass testing, which isn't something that we can work from! So please post here, for the command, and for further discussion. If you need to comment directly on lines of code, you can click on them in the master branch (or a commit) and then just copy paste the link here. Thanks!

**Comment by wkpalan** [comment]
Ya, sorry about that. It took me a while to get to the blame comment.

This seems to create a problem when loading images with absolute path, which sometimes is necessary depending on the location of the singularity image

```
Absolute Image location
/home/gokul/cloud/go_annotation/GOMAP-singularity/GOMAP.simg
Image location after loading
home/gokul/cloud/go_annotation/GOMAP-singularity/GOMAP.simg
ERROR  : Image path home/gokul/cloud/go_annotation/GOMAP-singularity/GOMAP.simg doesn't exist: No such file or directory
ABORT  : Retval = 255
```

```
Absolute Image location
/home/gokul/cloud/go_annotation/GOMAP-singularity/GOMAP.simg
Relateive Image location
../../../../../home/gokul/cloud/go_annotation/GOMAP-singularity/GOMAP.simg
Image location after loading
../../../../../home/gokul/cloud/go_annotation/GOMAP-singularity/GOMAP.simg
```

**Comment by vsoch** [comment]
Yes could you please give an exact command I can run to reproduce? I don't mean the error output, I mean the command :)

**Comment by wkpalan** [comment]
Also I installed the singulairy-cli from pip. Using `pip3 install spython`

**Comment by vsoch** [comment]
You can just get the image location like this:

```bash
image_loc = Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
```
I don't know what kind of black voodoo you are up to there, but it doesn't work :)

**Comment by wkpalan** [comment]
Could it be a symlink issue?

**Comment by vsoch** [comment]
I think you are missing the idea - that is a function that you call, and it returns an image path. What you are trying to do is construct your own path (outside of the function) and this is not the way to go about it. Try the line that I gave you and tell me what the variable `image_loc` is after. Are you fairly new to programming or python? If so, welcome!

**Comment by wkpalan** [comment]
Thanks. That makes more sense. I was following the documentation and must
have missed something about the image location.

Just to clarify, if the image is already at a specific location then can I
just use Client.run or Client.exec? Would I need to load the image file
with Client.load?

I thought I was sufficient I'm python  but guess I'm not.

**Comment by vsoch** [comment]
You can run the path too :)

$ client.load('/home/vanessa/Desktop/image.simg')
$ output = client.run()

**Comment by vsoch** [comment]
Oh and correct, if you have a client (regardless of the loaded image, or None loaded) you can give an argument to run, like:

```python
 output = client.run(image='/home/vanessa/Desktop/image.simg')
```

See the function (and arguments) here --> https://github.com/singularityhub/singularity-cli/blob/master/spython/main/run.py#L24

**Comment by wkpalan** [comment]
Thank you. That solves my problem.

**Comment by vsoch** [comment]
Awesome! Closing issue. Let me know if you need any more help.

**Comment by wkpalan** [comment]
#50 This should fix the issue, th strip command was stripping the path name
