### ISSUE TITLE
create dockerfile parser

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-cli#5]

**Comment by remyd1** [comment]
Hi @vsoch 

I am trying your parser to convert automatically Dockerfiles to Singularity recipes.

There are some spaces inserted in `%labels` section:

```
wget https://raw.githubusercontent.com/remyd1/containers-benchs/master/netperf/docker/dockerfile
spython recipe dockerfile
...
%labels
M A I N T A I N E R
C a r l o s   E d u a r d o   A r a n g o   < c a r l o s . a r a n g o . g u t i e r r e z @ c o r r e o u n i v a l l e . e d u . c o >
...
```
Otherwise, I ditn't notice any bug. 

Thanks !!

**Comment by vsoch** [comment]
haha thanks @remyd1 ! I will fix that asap!

**Comment by vsoch** [comment]
It looks kind of cool though, I must say :)

**Comment by vsoch** [comment]
This was merged,
