### ISSUE TITLE
some general ideas

### ISSUE THREAD

**Issue by al3x609** [singularityhub/singularity-cli#61]
- What do you think about binary wheel over egg distribution?
- conditional import in setup.py
```
try:
   from setuptools import setup, find_packages
except ImportError:
    from distutils.core import setup
```
-  try/except on read files example
```
try:
    with open(version_file) as filey:
        exec(filey.read(), lookup)

except (IOError, ImportError):
    lookup = ''

```

- create a template for ISSUE_TEMPLATE.md

___

## Expected Behavior

[ Please describe the behavior that are expecting ]

## Steps to Reproduce

[ Please provide detailed steps for reproducing the issue and reproducible Code Snippet ]

## Context

[provide more detailed introduction to the issue itself . This is for make a reproducible issue.]
* Operating System:
* singularity version:
* spython version:
* python version:

## Failure Logs

 [ log or files here. If relevant, include a screenshot]

## Possible Fix

[ the suggest fixes or reasons for the bug]

**Comment by vsoch** [comment]
The issue template is a great idea! We could even do different kinds (.e.g, bug vs.  question vs feature request). For the wheel vs. egg, how is this important for the software, or why your preference?

**Comment by vsoch** [comment]
hey @al3x609 check out the "Create issue" button now, we have three templates!

**Comment by al3x609** [comment]
it looks much more organized!

**Comment by vsoch** [comment]
Yeah I like it too 😊

**Comment by al3x609** [comment]
about wheel vs egg:
- The development in wheel is more active,
-  we can work more easy over virtualenv, so good about portability
- all build artifacts  can be packet for the same interpreter, then more easy for CI test and will automatically include the correct paths.
- the *.pyc files can be very confused in an install PATH, with wheel no more!
- less tied to a specific Python implementation. 
- wee no need more setup.py for install
- binary wheel distribution also can be generate egg-info too. 
- what about uninstall out of PYPi?
-- in egg: 
  `$python setup.py install --record install_log.txt`
  `$cat install_log.txt | xargs sudo rm -rf` :|
- wheel is versioned, and be standard like to _Standard Container Integration Format (SCI-F)_ :)

**Comment by vsoch** [comment]
distutils doesn't support some core things like entry_points, and if people have both they are going to see this message:

```
Cannot uninstall 'spython'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
It's not a standard per say, but in that everyone and his cousin is using setuptools, I don't see compelling reason to change it.

**Comment by al3x609** [comment]
hi a last thing, only for not open a new issue and close this, How I can run a container in detached mode and that this container not exit when root process (python script) exit?

- I need deploy a slurm interactive session 
- within the allocated resources, start a container for a user (python script and spython), which must continue running while the assigned time does not end, but if there is a failure in the network and even if the connection is lost or closed the terminal the deployed services are not lost.

_without API, I think launch a subprocess.Popen with nohub response like this:_

`subprocess.Popen(['nohup', 'singularity', 'run', 'test.img'],
                 stdout=open('/dev/null', 'w'),
                 stderr=open('logfile.log', 'a'))`
but with the API, Im no sure. 
I apologize if this question is something out of context.

**Comment by vsoch** [comment]
You would want to use a container instance!

https://singularityhub.github.io/singularity-cli/commands-instances

The functionality is still pretty limited, but it will let you start and stop and generally control.

If you are interested in running a container via slurm and then doing port forwarding, check out this tool I made for users on our cluster --> https://github.com/vsoch/forward

It has "ready to go" configurations and scripts for the clusters at Stanford, but I'd be happy to add one for your setup!

**Comment by al3x609** [comment]
apologize for all the spam that I am going to post here: $

... my workflow is as follows:
I am developing a SLURM node that allows to deploy applications with graphical interface for example Paraview, VisiT, Bleder, that runs on Linux containers.

through a python script with the docker API, for each user I deploy two containers: 1. (a web client vnc / proxy websocket / nginx) 2. (desired application / turboVNC).
This already did well with Docker; but because it was necessary for users to interact with the terminal to request the resources and lift the containers by means of environment modules and taking into account Docker's failures regarding security and privilege scalability, I decided to put a proxy against the " docker engine "to avoid creating more containers, and only run the available, after this by docker tests did not behave very well with mpi and" the namespaces / cgroups "of SLURM, so I read about singularity, and decided to port all the contenders, with the surprise that the latter interacts very well with slurm, mpi and facilitates the integration of GPU in the container, :) happiness up there ...

Now to automate everything, oh!
although I no longer have to map environment variables, data volumes, "nvidia-docker runtime", port mapping, $ HOME directory, etc ... inside the container, I see that singularity / spython is still in development and as far as has not implemented a process control within the container, therefore add to each container a script that does just that, lift the applications, control the execution time and finish the services according to the parameters that happened to the container which I take from the environment variables of the current session SLURM / interactive, but ... I am blocked in the part of raising all these services in an uncoupled way from the SSH session and that they keep running at the mercy of network failures. Docker allowed me to put an "init" process and undocked mode "-d", which is not yet implemented in its counterpart.

For now I do not need to automate everything that has to do with SHH and redirection of ports, it is an initial project and it would be difficult to familiarize new users with the platform.

that's why I'm here, to collaborate in what I can most and also learn more :)

**Comment by vsoch** [comment]
It sounds like to do this properly you need communication between containers, and also more functionality for singularity services. This is something to bring up on the Singularity boards --> https://github.com/singularityware/singularity. In this python client we don't implement anything new, it's a wrapper for singularity, so if the functionality isn't here then it needs to be added there first.

What the forward tool I showed you can do is launch a container as a SLURM job, from the user's computer, and forward the port so the web interface is accessible. The node keeps running as a job, and the container keeps running via whatever server was started. That's probably the most that I can offer, beyond tweaking of that tool to help with your goal.

**Comment by al3x609** [comment]
thank you very much, also your work is impressive in the HPC world, believe me that the tools you have developed are very useful, I will read them in detail, because among other words let's say I am a bit "new" in some things, but I challenge myself and learn on the fly, my ultimate goal is to convert the entire HPC center of my country to a web environment, where you can request jobs deploy containers, etc .. and what I can contribute to the development of spython as much as possible, because there is no better way to learn than by doing.

**Comment by vsoch** [comment]
Wow, your goals are very inspiring, and that might be one of the nicest things I've ever heard! I'm taking a screen shot so I can preserve it :O)

I think a container cluster will ultimately be what you are interested in, and I think Singularity will have integration with Kubernetes in a few months so you could start looking at that. Although I would say a setup with a job manager (SLURM or SGE) that lets users forward ports is a very decent start! Kubernetes is going to work a little like docker-compose in giving you a controller (kubectl) for groups of containers (called pods/deployments) that can be the basis for such a cluster. 

It sounds like you might enjoy some helpful resources for your learning?

 - [Google Experts](https://developers.google.com/experts/americas) might be a way to find someone local to you that you could ask questions about Kubernetes.
 - [Udacity](https://www.udacity.com/scholarships) has scholarships for training if you might benefit from this.

I'm sort of like you, I learn best by just diving in and building, but when you have an aspiration like that it can be helpful to surround yourself with really smart people. This might not be a "build it now" solution, but a lot of big HPC centers offer training conferences / internships or similar, so you could decide to do some kind of work study or immersion experience for 6 months to a year, and propose to have the focus be your project. That way you can be immersed in a pool of experts (everything from containers to slurm to general hpc) to meet with, share your ideas, learn what has already been done, etc. I would search around Google for the big centers (e.g., TACC, SDSC, University of Chicago) and then reach out to people with a general inquiry. If you have code / something to show this might be better so they see what you are working on.

**Comment by al3x609** [comment]
@vsoch Thanks a lot.
