### ISSUE TITLE
 errors not handled correctly in function [ spython/main/run.py. ] run()

### ISSUE THREAD

**Issue by al3x609** [singularityhub/singularity-cli#62]
## Expected Behavior

the function **run** should not get to execute this error **AttributeError: 'NoneType' object has no attribute 'strip'** in case of previous errors

like to:
ERROR Return Code -15: ( ... message ...)

## Actual Behavior
this a intencional test:
I deploy a container that ends all processes within it after a defined time, with a call to _kill_

the first error `ERROR Return Code -15` is correct because `subprocess.Popen.returncode` return -15 with the Unix signal SIGTERM=-15, sent by a call to kill;  

but I should not get to evaluate the sentence [result = result.strip('\n')](https://github.com/al3x609/singularity-cli/blob/20f820bc037206a3bf090043c578bdb29a7deaa2/spython/main/run.py#L94)

due to the error caught in the previous step

## Steps to Reproduce

-  start any container indefinitely
-  kill the principal process inside de container in another terminal.
- check the output in the first shell
route access 
`spyton.main.run.__init.__py._run_command -> Client._run_command  -> command.run_command -> run_cmd(utils.terminal.run_command )` => [subprocess.communicate()](https://github.com/al3x609/singularity-cli/blob/20f820bc037206a3bf090043c578bdb29a7deaa2/spython/utils/terminal.py#L134)
## Context
* Operating System: centos 7 64 bits
* singularity version: latest
* spython version: latest
* python version: 3.7

## Failure Logs

![image](https://user-images.githubusercontent.com/4086644/45405869-27f43e80-b62a-11e8-9f5f-055b2e805680.png)

## Possible Fix
before
````
    result = result.strip('\n')
````
after
```
    if(result):
        result = result.strip('\n')
```
![image](https://user-images.githubusercontent.com/4086644/45407194-4e1bdd80-b62e-11e8-8ce1-04a82b95b134.png)

**Comment by vsoch** [comment]
Agreed! Can you give me a dummy case to test this (and check the fix is sufficient?)

**Comment by al3x609** [comment]
yes, 

```
Bootstrap: docker

From: nginx

%runscript
exec   nginx
```
I made another test and find the real fail:
`---- Popen.communicate() returns a tuple (stdoutdata, stderrdata)----> lines(,).`

`terminal.py -> run_command() return a dict output={.'message': lines, 'return_code': process.returncode   }`

``` 
ìf ('return_code' == 0) -> command.py -> run_command() return  the 'message'  -> lines -> a tuple
---- Popen.communicate() returns a tuple (stdoutdata, stderrdata)----> lines(,).
```

- Now in run.py ->  line 94 **result = result.strip('\n')** fail because the tuples no has attribute .strip()

`for example if stdout=" " , lines value show ('2.6.0-HEAD.579c415\n',)`

-  previously what I did was to avoid the problem, not correct it :(


I'm not sure if we should suppress the error, because I have not read all the code where it can affect the most.

**Comment by vsoch** [comment]
hey @al3x609 my instinct is to be more conservative here - the run that we are looking at is starting a service, and logically it's not going to return a result in the same way as executing a container (like running a script to get a result). Since the general functions to run commands need to be just that, it seems correct that None is returned to them, and the bug is higher up assuming that it's *not* a service and trying to return a result. So instead of editing those functions, I've done your suggested fix to check for the result, and opened a PR here --> https://github.com/singularityhub/singularity-cli/pull/63 if you would care to review! Thank you!
