### ISSUE TITLE
 [Feature request] Singularity 3.*,  now supports arguments in %startscript for instances.

### ISSUE THREAD

**Issue by al3x609** [singularityhub/singularity-cli#81]
Hi Vanessa, 
the developers have added this functionality. 
It would be nice to have it in spython and not depend more on environment variables.

watch this

[Feature request](https://github.com/sylabs/singularity/issues/1966)

[pull merged](https://github.com/sylabs/singularity/pull/2512)

maybe these lines can be improved to include this functionality. e.g

https://github.com/singularityhub/singularity-cli/blob/7893bddf592a1b2ec884c529ed2a9eef2ad92670/spython/main/run.py#L73-L76

**Comment by vsoch** [comment]
Great that this was added! It looks like it was fairly easy to do too.

Let's talk about the specific functionality you are looking for. From spython, you want to:
 
 -  start an instance, and provide the arguments to it
 -  list instances, and see the args that were provided? 

The [instance start](https://github.com/singularityhub/singularity-cli/blob/7893bddf592a1b2ec884c529ed2a9eef2ad92670/spython/instance/cmd/start.py) code is under instance/cmd (you linked to run.py for running containers). The start command is what you are looking for, correct?

**Comment by al3x609** [comment]
the number one, 
* start an instance, and provide the arguments to it, e.g . start a web server with arguments inside a container, 

> The [instance start](https://github.com/singularityhub/singularity-cli/blob/7893bddf592a1b2ec884c529ed2a9eef2ad92670/spython/instance/cmd/start.py) code is under instance/cmd (you linked to run.py for running containers). The start command is what you are looking for, correct?

Im sorry, I was not clear where the %startcript code was. 👍

**Comment by vsoch** [comment]
Haha no worries, honestly I forgot too :)

Yep I'll get this underway for you soon!

**Comment by vsoch** [comment]
Just to be sure - is this for 3.0+, or 3.1+?

**Comment by al3x609** [comment]
from 3.0 forward. +

**Comment by vsoch** [comment]
okay cool! I threw something together really quickly (haven't tested) but will get a PR up for you so you can test away :)

**Comment by vsoch** [comment]
okay, here you go! https://github.com/singularityhub/singularity-cli/pull/82

**Comment by al3x609** [comment]
Hi, it works 👍:)  👍
 
my test.def

```
$cat test.def
BootStrap: docker

From: centos:latest

%startscript

echo "${@}"
```

`singularity instance start  test.sif test "hello world" "arg1" "arg2"`

```
$cat /home/alex/.singularity/instances/yaje/alex/test.out
hello world arg1 arg2 
```

___
```
singularity --version
singularity version 3.0.3-460.g049c5c6
```

**Comment by vsoch** [comment]
Awesome! I'll merge and release after dinner :) That was easy! *pushes staples button*

**Comment by vsoch** [comment]
Thanks for this request @al3x609 ! Merged and released https://pypi.org/project/spython/0.0.50/
