### ISSUE TITLE
[bug] We lost retrocompatibility with 2.* Singularity version.

### ISSUE THREAD

**Issue by al3x609** [singularityhub/singularity-cli#85]
a few months ago, we made a few changes for support Singularity 3.* instance group commands, 

i.e

https://github.com/singularityhub/singularity-cli/blob/f84ef3e8686691a28a885b5f568e1c7eceba69ab/spython/instance/cmd/stop.py#L31-L34

but this break compatibility with 2.* branch, because always go inside the IF statement,  it was my mistake, :( .

this can fix that.

`if ( get_singularity_version().find("version 3") != -1 ):`

now,  testing singularity 3.* commands, they now support two ways to return `singularity version`

_I think that they we listen to us :)_ 

- singularity version
3.1.0-rc4.dirty
- singularity --version 
singularity version 3.1.0-rc4.dirty

What you think about that? 

Can this return value be used to prevent including unnecessary code?

**Comment by vsoch** [comment]
Okay for the first part:

> but this break compatibility with 2.* branch, because always go inside the IF statement, it was my mistake, :( .

Can you give an example of why this would happen? Is it just a bug with how we used find? This is definitely easy to fix!

For the second part, for all of the versions you listed, why do some have "singularity version" and others not? And what do you mean by:

> Can this return value be used to prevent including unnecessary code?

Oh so instead of checking the string, just check the return value (is that what you mean?) That's a great idea!

**Comment by al3x609** [comment]
ok, for the first:

e.g in ipython:
first test
```
in [1]: version='singularity version 3.1.0-rc4.dirty'
in [2] version.find("version 3")
out [3]: 12

```

> If substring exists inside the string, it returns the index of first occurence of the substring.
If substring doesn't exist inside the string, it returns -1.

second test
```
in [1]: version='singularity version 3.1.0-rc4.dirty'
in [2] version.find("version 2")
out [3]: -1
```

now, no matter if the return value is a positive or negative, the IF statement always is executed,  and the variable **subgroup** always will be replaced with   **["instance", "stop"]** ,  

which gives an error in version 2. * of Singularity

i.e 

```
if(4):
 print("test")

test
__________________________________________________________________________________________________________
if(-1):
 print("test")

test
```

It is something simple, but many times simple things are the least we consider, and we will have an almost unperceptible logic error.


for the second part:


it's just a comment to show you that they return two different strings when looking for the singularity version. which can trigger errors for other applications that require this value, in this case Spython.

from your [comment](https://github.com/sylabs/singularity/issues/2376#issuecomment-439700827)

**Comment by vsoch** [comment]
Yep that's a bug! I'll start work on it now. I have a [PR here](https://github.com/singularityhub/singularity-cli/pull/84) for other instance tweaks, so I'll let you know when I've updated it (and if you could test the components involved, would be greatly appreciated).

Stay tuned!

**Comment by vsoch** [comment]
okay please test the PR. With respect to your observation, it's indeed the case that `singularity --version` returns a different result from `singularity version.` Since the flag was provided in the original command, and we have choice to use one or the other, we can have consistency in using it (and I don't see it being an issue).

**Comment by al3x609** [comment]
it works. your fix is more pythonic code :) , also i check the PR that returns an instance object instead of a List, and it works correctly.

with ipython, the next modules  are tested. 

- iutils.py
- start.py
- stop.py 
- instances.py

___

one more thing, the docstring for _Stop_ function needs to be updated.

https://github.com/singularityhub/singularity-cli/blob/e6fcbaa2eaef63fc8f7ced1f1fb6f6334b43e08e/spython/instance/cmd/stop.py#L12-L20

**Comment by vsoch** [comment]
Good call! Let me fix that quickly.

**Comment by vsoch** [comment]
okay, fixed! Take a look and let me know if it's ok now :)

**Comment by al3x609** [comment]
Oops, you forgot this line. :p

https://github.com/singularityhub/singularity-cli/blob/8097f245c22408c644b3c06ea4a7dbd0c12148c1/spython/instance/cmd/stop.py#L13
