### ISSUE TITLE
instance_stopall not stopping instances

### ISSUE THREAD

**Issue by adl2db** [singularityhub/singularity-cli#86]
## Expected Behavior

instance_stopall should stop all running instances.

## Actual Behavior

instance_stopall is not stopping any instances, getting a return code of 0

Tried using the command line of singularity using the command ``singularity instance stop --all`` to verify that stopping was possible and indeed the running instances stopped

## Steps to Reproduce

```Python
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from spython.main import Client as client
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        13818    /redacted/alpine_latest.sif

[instance://instance0]
>>> client.instance_stopall()
0
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        13818    /redacted/alpine_latest.sif

[instance://instance0]
>>> client.instance_stopall(sudo=True)
0
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        13818    /redacted/alpine_latest.sif

[instance://instance0]
```

## Context

[provide more detailed introduction to the issue itself . This is for make a reproducible issue.]
* Operating System: Ubuntu16.04
* singularity version:  3.0.1-94.g7de6fa2
* spython version: 0.0.51
* python version: 3.5.2

**Comment by vsoch** [comment]
Is there any chance that there is a different user running the spython client than the containers? The instances belong to the running user, so if you change user (either between users or between root and some regular user) you won't have a handle to control the other instances. 

If you could give me:

 -  the commands you used (outside of spython) to start the instance
 - the user that started the instance
 - the user running spython

the above should be good to reproduce your issue! Thanks much!

**Comment by adl2db** [comment]
The instance was started by the same user running the spython client. The user is a regular user with sudo permissions.

To start the container:  
``singularity instance start /path/to/image/alpine_latest.sif test_instance3``

Thanks!

**Comment by al3x609** [comment]
hi @vsoch , Im searching about that, 
 the issue is about this source code [instances.py](https://github.com/singularityhub/singularity-cli/blob/master/spython/main/instances.py)

We forgot update this for singularity 3.*

**Comment by vsoch** [comment]
@al3x609 please explain?

**Comment by al3x609** [comment]
https://github.com/singularityhub/singularity-cli/blob/67cf2f165fd8ba667347dd1c554843e2acfabdbb/spython/main/instances.py#L112-L114


look at this.
```
    cmd = 'instance.stop'

    if 'version 3' in get_singularity_version():
        cmd = ["instance", "stop"]

    cmd = cmd + ['--all']
    ...
```

**Comment by vsoch** [comment]
Ah nevermind I see what you mean! Yes we missed it! PR coming soon!

**Comment by vsoch** [comment]
here you go! https://github.com/singularityhub/singularity-cli/pull/87
