### ISSUE TITLE
test for singularity 3.+ over travis CI never gonna be executed 

### ISSUE THREAD

**Issue by al3x609** [singularityhub/singularity-cli#88]
https://github.com/singularityhub/singularity-cli/blob/67cf2f165fd8ba667347dd1c554843e2acfabdbb/.travis/before_install#L21

What is your position regarding creating integration tests for version 3 of singularity?

I think the ones that are now failed, in the case of porting them to spython for singularity 3. +

**Comment by vsoch** [comment]
It’s a good idea!

**Comment by al3x609** [comment]
@vsoch  this test function need to be updated 

https://github.com/singularityhub/singularity-cli/blob/307f0d28d26c98967d3fead60640d8fa9e943ba5/spython/tests/test_utils.py#L75-L85

e.g with ...

```
 def test_check_get_singularity_version(self): 
     '''check that the singularity version is found to be that installed''' 
     print("Testing utils.get_singularity_version") 
     from spython.utils import get_singularity_version 
     version = get_singularity_version() 
     self.assertTrue(version != "") 
     os.environ['SPYTHON_SINGULARITY_VERSION'] = "singularity version 3.1.0" 
     version = get_singularity_version() 
     self.assertTrue(version == "singularity version 3.1.0" )
```

**note**: Im no sure if the last releases of singularity 3.1.0 return the string "singularity version 3.1.0" 

for the command `singularity --version`; Im working with the main branch from the github repo, then my version string is: 'singularity version : 

>  "singularity version 3.1.0-29.ga78434c"

 '

**Comment by vsoch** [comment]
Need to figure out how to install GoLang before we get there @al3x609 !

**Comment by al3x609** [comment]
ok, I think the same as you, Golang is a very big dependency for this tool :(

**Comment by vsoch** [comment]
See commits here https://github.com/singularityhub/singularity-cli/pull/87 if you are interested in working on this.

**Comment by al3x609** [comment]
ok, I will see that to night. we talk later
bye 👍

**Comment by vsoch** [comment]
hey @al3x609 your wish has been granted! I took a few days because I wanted to do it right - I first made a set of Singularity Orbs to make installing Singularity across versions easy :point_right:  https://circleci.com/orbs/registry/orb/singularity/singularity then I came back here and re-wrote the config to use them. Now we have testing for 2 and 3.

**Comment by vsoch** [comment]
I'm going to close the issue, please re-open if needed! I'm going to work on adding the OCI commands to the client next.
